### ISSUE TITLE
how to set core-drawer-panel closed by default in core-scaffold component ?

### ISSUE THREAD

**Issue by thibault-perinet** [Polymer/core-scaffold#16]
I'd like to have a core-scaffold with the core-drawer-panel closed by default, and manage the state (open/close) of this drawer with the menuButton, regardless the responsiveWidth.
When trying to use togglePanel and closeDrawer methods ... get undefined error.
Thanks for help

**Comment by vinyll** [comment]
There's a undocumented `hidden` property.

```
Polymer({
   ready: function(){
      my_drawer.hidden = true;
   }
});
```
