### ISSUE TITLE
core-card disappeared

### ISSUE THREAD

**Issue by davenotik** [Polymer/core-scaffold#3]
Polymer Designer makes use of it, but it's nowhere to be found.

https://gist.github.com/DaveNotik/0548c1e6b520c95ff2a3

I notice in the commits it was added to core-scaffold?

**Comment by AaronLayton** [comment]
In the current Polymer and Paper collections there is no `polymer-ui-card` or `core-card`. Was these both removed and what is the current solution for these?

**Comment by pjjjv** [comment]
People keep asking about it: https://plus.google.com/u/0/+MarkFortner/posts/CRzFZWZPDou?cfem=1

**Comment by AaronLayton** [comment]
I have made my own version of the Polymer UI card - Could I submit this as a starting point @robdodson ?

**Comment by robdodson** [comment]
@frankiefu did you guys say you were working on a card recently?

**Comment by frankiefu** [comment]
@notwaldorf has made a paper card here: https://github.com/PolymerLabs/paper-card

**Comment by AaronLayton** [comment]
@frankiefu @notwaldorf that paper-card doesn't seem to have any `<paper-shadow>` built in to it

**Comment by addyosmani** [comment]
@AaronLayton Want to file a bug against paper-card so we can get that added?

**Comment by AaronLayton** [comment]
@addyosmani  I will do one better and submit a pull request later ;-)

**Comment by notwaldorf** [comment]
Oh yay, a PR would be great. I think I just inherited the style from swipeable-card, and didn't think about changing it :(
